/**/controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["left_front_wheel_joint", "left_rear_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint", "right_rear_wheel_joint"]

    wheel_separation:  0.195      # wheel_separation_width
    wheel_radius:      0.035      # wheel_radius

    cmd_vel_timeout: 0.5
    publish_rate: 50.0

    use_stamped_vel: false
    cmd_vel_unstamped_topic: "/cmd_vel"

    base_frame_id: base_footprint
    odom_frame_id: odom

    enable_odom_tf: true
    publish_odom: true